@baseUrl = http://localhost:3102



### TEST AUTH ###

### Créer un compte utilisateur (register)
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username":"test",
    "password":"toto"
}

###

### Se connecter (login)
POST {{baseUrl}}/me-connecter
Content-Type: application/json

{
    "nom_utilisateur":"test",
    "mdp":"toto"
}

###

### Se connecter (login)
GET {{baseUrl}}/miels
Content-Type: application/json



###

### Se connecter (login)
GET {{baseUrl}}/miels/1
Content-Type: application/json



###

### Se connecter (login)
GET {{baseUrl}}/miels/1/prix/10
Content-Type: application/json



###
### Se connecter (login)
DELETE {{baseUrl}}/miels/1
Content-Type: application/json



###

